### ISSUE TITLE
characters ` are missing after reorganize import

### ISSUE THREAD

**Issue by JR-Utily** [liancheng/scalafix-organize-imports#101] opened 2020-07-21 15:59 UTC
Hello !

In my company, we have a `macro` package in which we write our macros.
As macro is a reserved keyword, the package is name `macro` with backquote ` 

When we import something from this package, we write for example:

```
import com.company.`macro`.Dummy
```

but when this is reorganized, the ` are removed, and I have just:

```
import com.company.macro.Dummy
```
which is not a valid syntax and leads to compilation error

**Comment by liancheng** [comment] 2020-07-21 19:19
Hey @JR-Utily, thanks for reporting! Which version of `OrganizeImports` are you using? I think this issue has been addressed a while ago and here are some test cases:

- [`ImportsOrderSymbolsFirst.scala`](https://github.com/liancheng/scalafix-organize-imports/blob/f5ee0a86546e2f02edea3ad0644e83a77074f46a/input/src/main/scala/fix/ImportsOrderSymbolsFirst.scala)
- [`ExpandRelativeQuotedIdent.scala`](https://github.com/liancheng/scalafix-organize-imports/blob/f5ee0a86546e2f02edea3ad0644e83a77074f46a/input/src/main/scala/fix/ExpandRelativeQuotedIdent.scala)

**Comment by liancheng** [comment] 2020-07-21 19:23
@JR-Utily, actually, I reproduced this issue with the most recent master with the following diff:

```diff
diff --git a/input/src/main/scala/fix/ExpandRelativeQuotedIdent.scala b/input/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
index d91fe7f..59ed1ee 100644
--- a/input/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
+++ b/input/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
@@ -5,6 +5,7 @@ OrganizeImports.expandRelative = true
 package fix
 
 import QuotedIdent.`a.b`
+import QuotedIdent.`macro`
 import `a.b`.c
 import `a.b`.`{ d }`
 
diff --git a/output/src/main/scala/fix/ExpandRelativeQuotedIdent.scala b/output/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
index 24c79cb..633c3f3 100644
--- a/output/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
+++ b/output/src/main/scala/fix/ExpandRelativeQuotedIdent.scala
@@ -3,5 +3,6 @@ package fix
 import fix.QuotedIdent.`a.b`
 import fix.QuotedIdent.`a.b`.`{ d }`
 import fix.QuotedIdent.`a.b`.c
+import fix.QuotedIdent.`macro`
 
 object ExpandRelativeQuotedIdent
diff --git a/shared/src/main/scala/fix/QuotedIdent.scala b/shared/src/main/scala/fix/QuotedIdent.scala
index 010e8e2..121d61f 100644
--- a/shared/src/main/scala/fix/QuotedIdent.scala
+++ b/shared/src/main/scala/fix/QuotedIdent.scala
@@ -7,4 +7,6 @@ object QuotedIdent {
       object e
     }
   }
+
+  object `macro`
 }
```

Hmm, I guess it's because `macro` is a keyword. This might be a bug in the Scalafix/Scalameta side, though. At least this was the case the last time I tried to fix some quoted-identifier issue. Will take a look later.

**Comment by liancheng** [comment] 2020-07-21 19:40
Yeah, I believe the problem is in the Scalameta [`Scala.Names.encode()` method][1], which doesn't handle Scala keywords while quoting identifiers. Could be tricky to fix since it's outside `OrganizeImports`, but maybe we can hack a little bit...

[1]: https://github.com/scalameta/scalameta/blob/059f035259e180aa6bfee4b70fd5f16f3155ea7e/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala#L175-L185

**Comment by liancheng** [comment] 2020-07-23 06:27
The Scalameta side issue has been fixed in https://github.com/scalameta/scalameta/pull/2098, waiting for new releases of Scalameta and Scalafix.

**Comment by JR-Utily** [comment] 2020-07-23 16:13
Thank you so much for your reactivity !

**Closed** 2020-09-21 23:41 UTC
Labels: bug

**Comment by liancheng** [comment] 2020-09-22 05:50
@JR-Utily, a fix for this issue has been included in the v0.4.1 release.

**Comment by JR-Utily** [comment] 2020-09-29 13:11
Thanks !
Me and my team are very thankful !

**Comment by JR-Utily** [comment] 2020-10-06 07:52
I don't know why, I try to fix from 
```
import com.company.`macro`.{Dummy, DefaultImpl}
```
to 
```
import com.company.`macro`.Dummy
import com.company.`macro`.DefaultImpl
```

and it were not ok, it put it again as
```
import com.company.macro.Dummy
import com.company.macro.DefaultImpl
```

but after adding back the quotes in the defactorized lines, it keeps them correctly on next reorganize calls, so this is ok for me

but maybe there is still a bug (non-blocking this time)
